# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=250)),
            ],
        ),
    ]
